default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  template: template0

development: &development
  <<: *default
  username: vagrant
  password: vagrant
  database: wote

#production: &production
#  <<: *default
#  username: ~
#  password: ~
#  database: wote
