default: &default
  adapter: postgresql
  host: localhost
  template: template0

development: &development
  <<: *default
  username: vagrant
  password: vagrant
  database: wote

test: &test
  <<: *default
  username: vagrant
  password: vagrant
  database: wote

production: &production
  <<: *default
  username: ~
  password: ~
  database: wote
